version: '3.4'

services:
  python3:
    image: jobtime
    restart: always
    build:
      context: .
    container_name: jobtime
    tty: true
    volumes:
      - ./src:/usr/local/jobtime/src
      - ./resources:/usr/local/jobtime/resources
      - ./output:/usr/local/jobtime/output
